[package]
name = "dnsx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
log = "0.4.0"
env_logger = "0.9.0"
clap = { version="3.0.0", features = ["derive"] }
